name = "Google Scholar"

[[feeds]]
url = "https://kill-the-newsletter.com/feeds/u1qj9xi4h8i0ka4g2qo0.xml"
name = "Google Scholar Alerts"
max_articles = 5

[llm_settings]
n_most_important_news = 5
k_words_each_summary = 75

[content_extraction_settings]
follow_article_links = true
link_filter_pattern = "https:\\/\\/scholar.google.com\\/scholar_url\\?url=.+"
parser_type = "html.parser"

collection_prompt = "Una panoramica completa ma concisa degli articoli scientifici e delle ricerche presentate in questi articoli. La panoramica esclude le notifiche ricevute via email. Il destinatario è un esperto di machine-learning, musicologia, MIR e audio processing."
